### ISSUE TITLE
Service invoked too many times for one day: urlfetch

### ISSUE THREAD

**Issue by solifugo** [saitei/crypto-sheets#12]
Hi guys.

I got this problem after multiple tests yesterday:

`Service invoked too many times for one day: urlfetch. (line 219, file "Code")`

Not sure about the limits we have, but seems like I'm over it for today...

In google defence, during the tests I was doing, I added 10 different coins and created few new functions to get change by hour, 24h, 7days, name, symbol, marketcap.. so that means more than 50 calls to urlfetch per minute/execution... not good idea, I know.

Not sure if we can change the approach and get all data in 1 call to "https://api.coinmarketcap.com/v1/ticker/" and then "grep" the data we need from there?

**Comment by LeMoise** [comment]
Looks like we can only make 20,000 calls a day based on info from [this link](https://developers.google.com/apps-script/guides/services/quotas)

**Comment by solifugo** [comment]
I think im doing something very wrong...

Having 10 coins and 7 functions, I can only execute it less than 300 times.. hmmm

Need to understand how to avoid making a call to get each details

**Comment by LeMoise** [comment]
I have an idea on how to fix it. I'll play around with it today.

**Comment by solifugo** [comment]
Found this function that actually works, but is not 100% solution:

https://gist.github.com/varun-raj/5350595a730a62ca1954


```


function pullJSON() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheets = ss.getSheets();
  var sheet = ss.getActiveSheet();


  var url="https://api.coinmarketcap.com/v1/ticker/bitcoin/?convert=GBP"; // Paste your JSON URL here
  
   var response = UrlFetchApp.fetch(url); // get feed
  var dataAll = JSON.parse(response.getContentText()); //
  var dataSet = dataAll;
  
  
  var rows = [],
      data;
  

  for (i = 0; i < dataSet.length; i++) {
    data = dataSet[i];
    rows.push([data.id, data.name,data.price_gbp]); //your JSON entities here
  }

  dataRange = sheet.getRange(1, 2, rows.length, 3); // 3 Denotes total number of entites
  dataRange.setValues(rows);

}
```

**Comment by LeMoise** [comment]
Had the same idea, caches the info for an hour before refetching the url.

`if(cacheUSD == null){
  var url = 'https://api.coinmarketcap.com/v1/ticker/' + currencyId + '/';
  var response = UrlFetchApp.fetch(url, {'muteHttpExceptions': true});
  var json = response.getContentText();
  var data = JSON.parse(json);
  cache.put(currencyId, data, 3600)
  }
  
  return parseFloat(data[0]['price_usd']);
}`

**Comment by LeMoise** [comment]
This code works:

```
function getUSDRate(currencyId) {
  var cache = CacheService.getScriptCache();
  var cacheUSD = cache.get('price_usd');

if(cacheUSD != null){
ssRates.getRange('B5').setValue('cache');
  return parseFloat(cacheUSD[0]['price_usd']);
  
  }
  var url = 'https://api.coinmarketcap.com/v1/ticker/' + currencyId + '/';
  var response = UrlFetchApp.fetch(url, {'muteHttpExceptions': true});
  var json = response.getContentText();
  var data = JSON.parse(json);
  cache.put('price_usd', json, 3600);
  return parseFloat(data[0]['price_usd']);
}
```

I had to move these to the top of the code:
```
var queryString = Math.random();
var ss = SpreadsheetApp.getActiveSpreadsheet();
var ssRates = ss.getSheetByName('Rates');

```

**Comment by solifugo** [comment]
Let me check it tomorrow and see.

Could be a nice temporary solution, but I think someone posted a way to get the data directly into 1 variable and then, do the "gets" from it

**Comment by apiontek** [comment]
I added a pull req for a change that gets full /ticker/ api, stores in object variable, passes object var to getRate function, which gets rate from object rather than making call.

**Comment by saitei** [comment]
Try this out.  If it works I'll merge to master.
https://github.com/saitei/crypto-sheets/blob/develop/scripteditor.js

**Comment by apiontek** [comment]
It fails on symbol 'ZEN' (zencash) for me. Problem is the fetch URL ending in '?':

`var url = 'https://api.coinmarketcap.com/v1/ticker/?convert=' + targetCurrency + '&limit=0?';`

which for me results in `https://api.coinmarketcap.com/v1/ticker/?convert=usd&limit=0?`

For some reason with the extra `?` on the end, the returned results don't include zencash. Haven't checked if any other coins are missing. I'm not sure why the extra `?` is there.

When I remove it, everything works fine. I believe the line should be

`var url = 'https://api.coinmarketcap.com/v1/ticker/?convert=' + targetCurrency + '&limit=0';`

**Comment by solifugo** [comment]
Try this:

https://api.coinmarketcap.com/v1/ticker/?start=1&limit=2000

For what I understand, the API has around 1200 coins

**Comment by solifugo** [comment]
With USD / GBP:

https://api.coinmarketcap.com/v1/ticker/?start=1&limit=2000&convert=USD

https://api.coinmarketcap.com/v1/ticker/?start=1&limit=2000&convert=GBP

**Comment by apiontek** [comment]
Works fine for me with limit=0

**Comment by solifugo** [comment]
Ahh, ok sorry. I thought it didn't work with the limit=0..it was just the '?' at the end..

**Comment by solifugo** [comment]
Current code only needs 1 fetch independently of the number of coins.. So let's close this
