### ISSUE TITLE
EMC2 returns an error 

### ISSUE THREAD

**Issue by iKrazy** [saitei/crypto-sheets#15]
line90:    while (coins[n]['symbol'] !== myCoins[i]) {

TypeError: Cannot read property "symbol" from undefined. (line 90, file "Code")

**Comment by iKrazy** [comment]
This is because of coinmarketcap not pulling up certain coins in the pull.

**Comment by solifugo** [comment]
Hmm.. looks like you will need to do an exception and setup a call for that one with its coinmarket ID:

https://api.coinmarketcap.com/v1/ticker/Einsteinium/

Let me see if there is a way to make sure we get all the coinmarketcap coins

**Comment by solifugo** [comment]
Ok, I think this is working:

https://api.coinmarketcap.com/v1/ticker/?start=1&limit=1000

Let me check with the gurus later if we can add that way so we dont miss any coin. And please, report any other issue you can find so we get it fixed :)

**Comment by iKrazy** [comment]
1372 might have been how many they support when you queried the api. It is showing 1381 for me, so might be good to set a limit of 2000 for now.

**Comment by iKrazy** [comment]
`  var url = 'https://api.coinmarketcap.com/v1/ticker/?convert=' + targetCurrency + '&limit=1500?';`

to 

`  var url = 'https://api.coinmarketcap.com/v1/ticker/?start=1&limit=1500';`

**Comment by solifugo** [comment]
No need. The code includes "no limit" now
https://api.coinmarketcap.com/v1/ticker/?convert=' + targetCurrency + '&limit=0?';

**Comment by iKrazy** [comment]
Need to remove the ? after limit=0 or it will still break on EMC2.
