### ISSUE TITLE
Cannot call method "getRange" of null. (line 42, file "Code")

### ISSUE THREAD

**Issue by brobro16** [saitei/crypto-sheets#17]
Only new to this have not used google script before. 

Created new sheet called "Rates" pasted the contents of scripteditor.js file into panel.

Tried to run then by means of Run -> RunFunction -> getData  but then get a compile error:
Cannot call method "getRange" of null. (line 42, file "Code")

Probably something simple I am doing or not doing. Thanks

**Comment by zagnuts** [comment]
Make sure you name the sheet (ie the tab on the bottom) 'Rates'. The google spreadsheet is actually a document, with the script a macro in that document. I did the same thing - been using Excel for too long. ;-)

**Comment by solifugo** [comment]
@brobro16 can you please confirm if you have solved the problem? If yes, please let's close the issue

**Comment by brobro16** [comment]
yes that was it thanks - Needed to name the sheet.  ;)
