### ISSUE TITLE
BTM Bytom/Bitmark Mixup

### ISSUE THREAD

**Issue by iKrazy** [saitei/crypto-sheets#18]
Symbol BTM returns coin Bytom, but I am looking to return BTM Bitmark.

**Comment by solifugo** [comment]
Please, paste your code and the coins you want to "get" so we can check

**Comment by iKrazy** [comment]
`var queryString = Math.random();
var ss = SpreadsheetApp.getActiveSpreadsheet();

var ssRates = ss.getSheetByName('Rates');

var targetCurrency = 'usd'

// Grabs all CoinMarketCap data
if (typeof targetCurrency == 'undefined' || targetCurrency == '') {targetCurrency = 'usd'};
var coins = getCoins();

function getData() {

  // ===== Coins to Track ======
  // Enter the coins you want tracked, each one on a new line, in single quotes, followed by a comma
  // Use the value in the 'symbol' field here: https://api.coinmarketcap.com/v1/ticker/?limit=0
  // ===========================
  var myCoins = [
    'ARDR',
    'BTM',
    'DGB',
    'DOGE',
    'EMC2',
    'ETH',
    'FLDC',
    'LBC',
    'LSK',
    'MAID',
    'NAV',
    'NXT',
    'OMG',
    'PASC',
    'PPC',
    'REP',
    'RIC',
    'SBD',    
    'SC',
    'XLM',
    'SYS',
    'VIA',
    'VRC',
    'VTC',
    'XCP',
    'XRP',
    'XMR',
  ]

  // Creates column headers.  Don't change unless you know what you're doing.
  // If there is data you don't want, just hide the column in your spreadsheet, or simply don't reference it
  // DO NOT TOUCH
  ssRates.getRange('A1').setValue("ID");
  ssRates.getRange('B1').setValue("Name");
  ssRates.getRange('C1').setValue("Symbol");
  ssRates.getRange('D1').setValue("Rank");
  ssRates.getRange('E1').setValue("Price USD");
  ssRates.getRange('F1').setValue("Price BTC");
  ssRates.getRange('G1').setValue("24H Volume USD");
  ssRates.getRange('H1').setValue("Market Cap USD");
  ssRates.getRange('I1').setValue("Available Supply");
  ssRates.getRange('J1').setValue("Total Supply");
  ssRates.getRange('K1').setValue("Max Supply");
  ssRates.getRange('L1').setValue("Percent Change 1H");
  ssRates.getRange('M1').setValue("Percent Change 24H ");
  ssRates.getRange('N1').setValue("Percent Change 7D");
  ssRates.getRange('O1').setValue("Last Updated");
  // Adds in extra column headers if non-USD currency was chosen
  if (typeof targetCurrency !== 'usd') {
    ssRates.getRange('P1').setValue("Price " + targetCurrency.toUpperCase());
    ssRates.getRange('Q1').setValue("24H Volume " + targetCurrency.toUpperCase());
    ssRates.getRange('R1').setValue("Market Cap " + targetCurrency.toUpperCase());
  };


  // Creating new Object with our coins for later use.  
  // Each Object's key is the coin symbol
  var myCoinsObj = {};
  var myCoinsCount = myCoins.length;
  for (var i = 0; i < myCoinsCount; i++) {
    var n = 0;
    while (coins[n]['symbol'] !== myCoins[i]) {
      n++;
    }
    
    myCoinsObj[coins[n]['symbol']] = coins[n];
        
    ssRates.getRange('A'+(i+2).toString()).setValue(myCoinsObj[myCoins[i]]['id']);
    ssRates.getRange('B'+(i+2).toString()).setValue(myCoinsObj[myCoins[i]]['name']);
    ssRates.getRange('C'+(i+2).toString()).setValue(myCoinsObj[myCoins[i]]['symbol']);
    ssRates.getRange('D'+(i+2).toString()).setValue(myCoinsObj[myCoins[i]]['rank']);
    ssRates.getRange('E'+(i+2).toString()).setValue(myCoinsObj[myCoins[i]]['price_usd']);
    ssRates.getRange('F'+(i+2).toString()).setValue(myCoinsObj[myCoins[i]]['price_btc']);
    ssRates.getRange('G'+(i+2).toString()).setValue(myCoinsObj[myCoins[i]]['24h_volume_usd']);
    ssRates.getRange('H'+(i+2).toString()).setValue(myCoinsObj[myCoins[i]]['market_cap_usd']);
    ssRates.getRange('I'+(i+2).toString()).setValue(myCoinsObj[myCoins[i]]['available_supply']);
    ssRates.getRange('J'+(i+2).toString()).setValue(myCoinsObj[myCoins[i]]['total_supply']);
    ssRates.getRange('K'+(i+2).toString()).setValue(myCoinsObj[myCoins[i]]['max_supply']);
    ssRates.getRange('L'+(i+2).toString()).setValue(myCoinsObj[myCoins[i]]['percent_change_1h']);
    ssRates.getRange('M'+(i+2).toString()).setValue(myCoinsObj[myCoins[i]]['percent_change_24h']);
    ssRates.getRange('N'+(i+2).toString()).setValue(myCoinsObj[myCoins[i]]['percent_change_7d']);
    ssRates.getRange('O'+(i+2).toString()).setValue(myCoinsObj[myCoins[i]]['last_updated']);
    if (typeof targetCurrency !== 'usd') {
      ssRates.getRange('P'+(i+2).toString()).setValue(myCoinsObj[myCoins[i]]['price_' + targetCurrency]);
      ssRates.getRange('Q'+(i+2).toString()).setValue(myCoinsObj[myCoins[i]]['24h_volume_' + targetCurrency]);
      ssRates.getRange('R'+(i+2).toString()).setValue(myCoinsObj[myCoins[i]]['market_cap_' + targetCurrency]);
    };
  }
}
  
  //
  // DON'T TOUCH ANYTHING BELOW
  // IT MAKES THE MAGIC HAPPEN
  //

function getCoins() {

  var url = 'https://api.coinmarketcap.com/v1/ticker/?convert=' + targetCurrency + '&limit=0';
  var response = UrlFetchApp.fetch(url, {'muteHttpExceptions': true});
  var json = response.getContentText();
  var data = JSON.parse(json);
  
  return data;
}

`

**Comment by iKrazy** [comment]
Formatting messing up when I try to post here. https://pastebin.com/WEkwT8p5

**Comment by solifugo** [comment]
https://api.coinmarketcap.com/v1/ticker/?&limit=0

Can you check (sorry my mobile can't do the search for the whole list) if they actually have same symbol? (BTM)

**Comment by iKrazy** [comment]
No worries, yes they both have the symbol BTM, but Bytom is a higher rank than Bitmark.

**Comment by solifugo** [comment]
We had the code to search for "id" before, but adding the coin symbol was easier and friendly..

We may need to go back to id or check for other options

**Comment by iKrazy** [comment]
Would it be easier to add a part for exceptions? if the id = ___ then skip it until the next instance of the symbol type thing.

**Comment by solifugo** [comment]
I think that will make things more complex.

"id" should be unique, so I think will be a good idea to use it 

Can't imagine the confusion in the exchanges with that...

**Comment by iKrazy** [comment]
True. Changing to using 'id' and changing the symbols to ids worked.

**Comment by saitei** [comment]
Weird, good catch.  I thought symbols were unique as well.  That's an oversight on my part.  I changed it to symbols because it's more of a pain for people to look through the api list to find the correct ID.  I think we may just need to provide a list that's updated periodically with the `name`, `id`, and `symbol` of the coins in the API.
