### ISSUE TITLE
TypeError: Cannot read property "symbol" from undefined. (line 80, file "Code")

### ISSUE THREAD

**Issue by grutty** [saitei/crypto-sheets#19]
I'm getting this error when adding coins to my list. The list works fine. But when I add any additional symbols, I get this error: TypeError: Cannot read property "symbol" from undefined. (line 80, file "Code")

Line 80:  while (coins[n]['symbol'] !== myCoins[i]) {

//My list. I've tested adding multiple different symbols and keep getting the error. e.g.: 'PAC', 

  var myCoins = [
    'ARK',
    'BTC',
    'BCH',
    'ETH',
    'XRP',
    'XMR',
    'LTC',
    'MIOTA',
    'XEM',
    'DASH',
    'XLM',
    'NEO',
    'QTUM',
    'DOGE',
  ]

I've tried adding different symbols but keep getting the error.

**Comment by zagnuts** [comment]
Check your "Rates" sheet and see where it gets up to before stopping. Alternatively, comment out all but the original list and then slowly add your coins in a few at a time & manually run the script until you eventually find which is causing the issue.

I found that one of my coins (or rather a token) broke things so I have to do that one manually. In my case it was "Simple Token" which has (or rather had - they seemed to have just updated it) a symbol of OST (now changed to ST) but required "Simple-Token" when using the API.
