### ISSUE TITLE
getCoins url doesn't fetch some coins

### ISSUE THREAD

**Issue by apiontek** [saitei/crypto-sheets#21]
As previously [mentioned here](https://github.com/saitei/crypto-sheets/issues/12#issuecomment-354589785) the getCoins URL has an extra `?` at the end which, for whatever reason, causes some coins to be excluded.

For some reason with the extra `?` on the end, the returned results contain only the top 100 coins, same as without "limit=0" ... so the fix has been negated. I'm not sure why the extra `?` is there.

When I remove it, everything works fine. All 1300+ coins are retrieved. I believe the line should be:

`var url = 'https://api.coinmarketcap.com/v1/ticker/?convert=' + targetCurrency + '&limit=0';`

Even better, just stick the `limit=0` in there first and then it looks cleaner, one less string split:

`var url = 'https://api.coinmarketcap.com/v1/ticker/?limit=0&convert=' + targetCurrency;`

**Comment by solifugo** [comment]
I think we have pull request for that already:

https://github.com/saitei/crypto-sheets/pull/20

**Comment by iKrazy** [comment]
#20 got merged can you close this please @apiontek

**Comment by saitei** [comment]
@iKrazy Closing
