### ISSUE TITLE
Update Readme to include Refresh Button 

### ISSUE THREAD

**Issue by ddarbs** [saitei/crypto-sheets#24]
Sloppy editing but you get the idea.

![image](https://user-images.githubusercontent.com/982923/34544430-d977f16e-f0ab-11e7-87cb-f557da045707.png)

![image](https://user-images.githubusercontent.com/982923/34544412-b9e82f1c-f0ab-11e7-9d18-314386cfb159.png)

![image](https://user-images.githubusercontent.com/982923/34544456-00715f08-f0ac-11e7-9ffa-3844d7dca279.png)

![image](https://user-images.githubusercontent.com/982923/34544482-2c6419d4-f0ac-11e7-83f5-d8bdb38db427.png)

![image](https://user-images.githubusercontent.com/982923/34544524-60f93a76-f0ac-11e7-9958-5f17af36e8d6.png)

![image](https://user-images.githubusercontent.com/982923/34544580-aeb6820a-f0ac-11e7-9b06-ee0193f4ab81.png)

To interact with the drawing after assigning a script you need to first right click the drawing.

**Comment by LesterCovax** [comment]
IIIIII had no idea you could do that.  On the flip side, if you use the `From spreadsheet` > `on open` trigger,  you can simply refresh the page to trigger it.

**Comment by ddarbs** [comment]
I have all three, on open, every 30 min, and refresh button, set up :)

**Comment by Project-42** [comment]
wow, that is a great idea. Thanks for sharing!

**Comment by ddarbs** [comment]
Found another way to have a refresh option. You would still need to set a trigger to run this on spreadsheet open.

```
function onOpen() {
  var entries = [{
    name: 'Refresh',
    functionName: 'getData'
  }];
  ss.addMenu('Crypto Sheets', entries);
};
```
