### ISSUE TITLE
TypeError: impossible to get data error at "getRange" di null. (riga 61, file "Codice")

### ISSUE THREAD

**Issue by whatgrindsmygear** [saitei/crypto-sheets#28]
#if i try to run the code, like in the last screenshot of the first part, and get the data, i get an error in line 61

![error](https://user-images.githubusercontent.com/34898071/34801297-30a96082-f668-11e7-8ad1-a9dfcaf42ed0.PNG)

**Comment by Project-42** [comment]
Hi, looks like a different code version.
It looks like code could be missing the Rates sheet in your file.

Please, check you are using current script. Will mke easier to know what is the issue.

Once you have that, check both guides to make sure you setup the code into your spreadsheet file:

https://github.com/saitei/crypto-sheets/blob/develop/README.md

https://github.com/saitei/crypto-sheets/wiki/Easy-guide-(I-hope)-to-create-a-Portfolio-Tracker

**Comment by LesterCovax** [comment]
@whatgrindsmygear Looks like you may not have created a `Rates` sheet
