### ISSUE TITLE
Added LTC and other Scrypt coins via https://chainz.cryptoid.info/

### ISSUE THREAD

**Issue by GeekBoxIT** [saitei/crypto-sheets#29]
Found cryptoID Explorer while I was searching for one that would do LTC. Here is how I did LTC (essentially copied VTC)
https://chainz.cryptoid.info/

**cryptoID API Info:** https://chainz.cryptoid.info/api.dws

Under the Wallet Balance Configuration

    // ===== LTC wallet balances =======
    // Add more as needed with different variable names
    // Change the value in getRange() to match the cell in spreadsheet
    // Change the value in setValue() to match the variable above
    // =================================
  
    // LTC Wallet Comment
    var ltcWallet = getLtcBalance("LTC Wallet Here";
    ssWallets.getRange('B8').setValue(ltcWallet);

  
 Under the other functions near bottom 
  
    function getLtcBalance(ltcAddress) {
  
    var url = 'https://chainz.cryptoid.info/ltc/api.dws?q=getbalance&a='+ltcAddress;
    var response = UrlFetchApp.fetch(url, {'muteHttpExceptions': true});
    var balance = response.getContentText();
    //Pause to not trigger API limit for multiple wallets
    Utilities.sleep(300);
  
    return balance;
    }

**Comment by ddarbs** [comment]
Added in #31

**Comment by LesterCovax** [comment]
merged
