### ISSUE TITLE
Script permission security issue

### ISSUE THREAD

**Issue by TommySollen** [saitei/crypto-sheets#30]
When trying to add the getdata trigger the document owner is asked to approve the following permissions:

- Create new spreadsheets
- View and modify existing spreadsheets
- Share spreadsheets with others

Does this in fact mean the script has access to all the owner's spreadsheets?

**Comment by ddarbs** [comment]
@saitei @solifugo 

Adding the below snippet to the top of the script will change this, #31 

```
/**
 * @OnlyCurrentDoc
 */
```
https://developers.google.com/apps-script/guides/services/authorization

**Comment by LesterCovax** [comment]
Fixed in #31
