### ISSUE TITLE
TypeError: Cannot read property "id" from undefined. (line 102, file "Code")

### ISSUE THREAD

**Issue by srnka** [saitei/crypto-sheets#32]
Hello there I am getting this error, crosschecked IDs on the list and all are correct. 

Any thoughts? 

thanks 👍

**Comment by LesterCovax** [comment]
Can you create a patebin of your list of coins in the script?

**Comment by srnka** [comment]
Hey I managed to get it working have made a silly mistake and that was pulling script from GitHub not local, it works now :). 

Thanks a lot for your work :) 

![capture](https://user-images.githubusercontent.com/9066404/35271562-68ffa0e2-002a-11e8-9c61-f64776d75336.PNG)

**Comment by rapt-up** [comment]
Hello, I am getting the same TypeError. I added more to myCoins list and when I hit the button to run data this message came up. Not sure how to fix it. Suggestions?

The TypeError directed me to this line of code:

   while (coins[n]['id'] !== myCoins[i]) {

Thank you!
