### ISSUE TITLE
TypeError: Cannot read property "id" from undefined. (line 134, file "Code")

### ISSUE THREAD

**Issue by rapt-up** [saitei/crypto-sheets#39]
Hello, I am getting the same TypeError that another user experienced in one of the closed issues. I added more coins to myCoins list and when I hit the button to run data this message came up. Not sure how to fix it. Suggestions?

The TypeError directed me to this line of code:

while (coins[n]['id'] !== myCoins[i]) {

which is line 100 in your crypto-sheets/scripteditor.js

Thank you!

**Comment by ddarbs** [comment]
Can you copy your entire script to a pastebin and link it here please? I would guess that one of the coins isn't formatted correctly.

How it should be: `'bitcoin',` 

How you might have it: `'bitcoin'`

**Comment by rapt-up** [comment]
https://pastebin.com/4xC9qpUp

**Comment by iKrazy** [comment]
`‘chainlink’` to `‘chainlink’,`

**Comment by rapt-up** [comment]
I tried it a couple times and it still causes the same error

**Comment by ddarbs** [comment]
'ox' isn't a coin, are you looking for 'ox-fina'?

**Comment by rapt-up** [comment]
"id": "0x", 
        "name": "0x", 
        "symbol": "ZRX",

**Comment by ddarbs** [comment]
The script will pull by `"id"`, so you would use `'0x'` instead of `'ox'`. Let me know if that works for you.

**Comment by rapt-up** [comment]
Thank you so much, that was it!
