### ISSUE TITLE
Permit to change the numeric separator

### ISSUE THREAD

**Issue by pierrediancourt** [saitei/crypto-sheets#42]
Just a proposition :

I had to add a replace to change the dots as commas in numbers in get to get my calculus against this sheet to work.
That's a dirty way and i'm sure you can make it better with a configurable variable before the "do not change below" section.

`    ssRates.getRange('A' + r).setValue(myCoinsObj[myCoins[i]]['id']);
    ssRates.getRange('B' + r).setValue(myCoinsObj[myCoins[i]]['name']);
    ssRates.getRange('C' + r).setValue(myCoinsObj[myCoins[i]]['symbol']);
    ssRates.getRange('D' + r).setValue(myCoinsObj[myCoins[i]]['rank']);
    ssRates.getRange('E' + r).setValue(myCoinsObj[myCoins[i]]['price_usd'].replace(".",","));
    ssRates.getRange('F' + r).setValue(myCoinsObj[myCoins[i]]['price_btc'].replace(".",","));
    ssRates.getRange('G' + r).setValue(myCoinsObj[myCoins[i]]['24h_volume_usd'].replace(".",","));
    ssRates.getRange('H' + r).setValue(myCoinsObj[myCoins[i]]['market_cap_usd'].replace(".",","));
    ssRates.getRange('I' + r).setValue(myCoinsObj[myCoins[i]]['available_supply'].replace(".",","));
    ssRates.getRange('J' + r).setValue(myCoinsObj[myCoins[i]]['total_supply']);
    ssRates.getRange('K' + r).setValue(myCoinsObj[myCoins[i]]['max_supply']);
    ssRates.getRange('L' + r).setValue(myCoinsObj[myCoins[i]]['percent_change_1h'].replace(".",",")+'%');
    ssRates.getRange('M' + r).setValue(myCoinsObj[myCoins[i]]['percent_change_24h'].replace(".",",")+'%');
    ssRates.getRange('N' + r).setValue(myCoinsObj[myCoins[i]]['percent_change_7d'].replace(".",",")+'%');
    ssRates.getRange('O' + r).setValue(new Date((myCoinsObj[myCoins[i]]['last_updated'])*1000));
    if (targetCurrency !== 'usd') {
      ssRates.getRange('P' + r).setValue(myCoinsObj[myCoins[i]]['price_' + targetCurrency].replace(".",","));
      ssRates.getRange('Q' + r).setValue(myCoinsObj[myCoins[i]]['24h_volume_' + targetCurrency].replace(".",","));
      ssRates.getRange('R' + r).setValue(myCoinsObj[myCoins[i]]['market_cap_' + targetCurrency].replace(".",","));
    };`

Nice little tool btw =)

**Comment by ddarbs** [comment]
I think the general users of this sheet will use periods instead of commas when doing math. Any thoughts?
 @LesterCovax @solifugo

**Comment by LesterCovax** [comment]
Yeah, I'd say that the regions that use commas in that circumstance are less represented in the user base.  My recommendation would be to not edit the code but instead use custom formatting within the spreadsheet.

You can easily change it without any code changes by going to `File > Spreadsheet Settings > Change Locale` or set it in the script with something like `spreadsheet.setSpreadsheetLocale('de');` at the top.

**Comment by pierrediancourt** [comment]
Agreed, seems right :)
