### ISSUE TITLE
TypeError: Cannot read property "id" from undefined. (line 122, file "Code")

### ISSUE THREAD

**Issue by anubhavyadav** [saitei/crypto-sheets#43]
how will we remove this error, please let me know if anything else is required
![screenhunter_ mar 01 11 04 21](https://user-images.githubusercontent.com/32266762/36828547-84a4bf20-1d40-11e8-85f2-a256dc06e3a5.jpg)

**Comment by ddarbs** [comment]
One of your id’s under MyCoins doesn’t have a match on cmc. Can you post your code?

**Comment by ddarbs** [comment]
@jovianastronaut Working?

**Comment by linglung** [comment]
Hi 
Same error here. Just change 'Raiblocks' to "nano" since Raiblock has rebranded it's name and CMC already updated. 

var myCoins = [
    'ark',
    'bitcoin-cash',
    'bitcoin',
    'ethereum',
    'digibyte',
    'litecoin',
    'monero',
    '**nano**',
    'vertcoin'
  ]
